language: node_js
node_js:
- '4.0'
- '7.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
      secure: Rcq68neE4v0LstiDFdSfKXZNTNLzpcVir/UBr5SSyY0ygNymEN+QSjf/XEwUr/B6OC39u5xU76crkAPO+j4fwKHGY7Au+hDchz29QTzzVfvxjp36O7IJNz+P2L7zA5d/iCFoUKgKDJHQ6tTpVMGB09u1YM1zlbIvWF7NSxroMuE=
    on:
      tags: true
      node: '4.0'
  - provider: releases
    api_key:
      secure: aeYd/dNJUP5qKRVaG5GRDiyaq95dk1dze7biJfq2ZjyV9NkgjLqUnjPDVr8m3H8JDyYkPs+SSu5wk/0FXfVPuVU4j5uOE/QSDolM++BSCdO36WetSjWzVNJEv9z9YmrBu+OyrMgUYM7wG7OMlsR+aHqPUwpZHbsUdIiUQO87G0E=
    file:
      - "match-casing.js"
      - "match-casing.min.js"
    on:
      tags: true
      node: '7.0'
