language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: OXSGjrw/rBn+m0ivebLeLRBVbWGFKBeSRcowBHBWeBIbBoEog9ZcRyQHRR+t+/JnHB/zyYHwAgsirs2FEQ9UMYwvg2gh5W9E0BwrqOoiiF6iB3IOulmokkx/39YDYo/QI/ErC9+SIvxawsaxcdvLzCtuieYsucb0lCH91ZrSaGA=
  file:
    - 'nlcst-affix-emoticon-modifier.js'
    - 'nlcst-affix-emoticon-modifier.min.js'
  on:
    tags: true
