language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: aeYd/dNJUP5qKRVaG5GRDiyaq95dk1dze7biJfq2ZjyV9NkgjLqUnjPDVr8m3H8JDyYkPs+SSu5wk/0FXfVPuVU4j5uOE/QSDolM++BSCdO36WetSjWzVNJEv9z9YmrBu+OyrMgUYM7wG7OMlsR+aHqPUwpZHbsUdIiUQO87G0E=
  file:
    - "nlcst-affix-emoticon-modifier.js"
    - "nlcst-affix-emoticon-modifier.min.js"
  on:
    tags: true
    node: '9.0'
